### ISSUE TITLE
Crash upon click for some

### ISSUE THREAD

**Issue by oflatt** [oflatt/space-orbs#8] opened 2015-12-03 04:29 UTC
For two of my friends with fancy computers, when they shoot in space orbs it crashes. They can move, but if they shoot it crashes. Might have to do with the cylinder call in pict3d.

**Comment by oflatt** [comment] 2015-12-07 03:50
I got the full error message from one of my friends.
![space-orbs-click-bug1](https://cloud.githubusercontent.com/assets/8523445/11618662/0a4f3358-9c5b-11e5-96f5-3e025d089e7b.png)
![space-orbs-click-bug2](https://cloud.githubusercontent.com/assets/8523445/11618658/fe5e5448-9c5a-11e5-88f6-d1d391536414.png)

**Comment by jeapostrophe** [comment] 2015-12-07 14:24
Can you say what graphics card and OpenGL versions you have?

**Comment by oflatt** [comment] 2015-12-07 23:47
I will ask. What is a good program for getting the OpenGL version? Is there a way to view it in windows 7 built in?

**Comment by oflatt** [comment] 2015-12-08 01:28
He has a gtx 770

**Comment by jeapostrophe** [comment] 2015-12-08 19:30
This is the same error as https://github.com/ntoronto/pict3d/issues/33 and the root cause is that the shader isn't casting a value to a float. Some OpenGL implementations like Intel and AMD's don't seem to enforce this GLSL rule. I will shortly update pict3d and I'll let you know so you can re-test.

**Comment by oflatt** [comment] 2015-12-08 20:53
Thank you!

**Comment by jeapostrophe** [comment] 2015-12-21 16:00
I believe this is fixed now on https://github.com/jeapostrophe/pict3d (you should be able to `raco pkg update pict3d` and get the new version)

If it is not working for you, can you send me the output of `racket -l pict3d/tests/shaders` please

**Closed as completed** 2018-11-04 15:03 UTC
Labels: bug
